config/routes.rb
Rails.application.routes.draw do
	root	'bookmarks#index'
	get	'bookmarks'	=> 'bookmarks#index'
	get 'domains'		=> 'domains#index'
	match 'tagged', to: 'microposts#tagged', :as => 'tagged', via: 'get'
 	
	resources :bookmarks
  resources :domains

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :domain

	acts_as_taggable

	validates :name, 	presence: true
	validates :url,		presence: true, uniqueness: true,
										format: URI::regexp(%w(http https))
	
	# Returns a domain from the URL.
	def extract_domain
		parsed_url = URI.parse(url)
		return parsed_url.host
	end

	def update_domain
		ed = extract_domain

		if (Domain.find_by(domain: ed)).nil?
			Domain.create(domain: ed)
		end
		update(domain_id: Domain.find_by(domain: ed).id)
	end

	def generate_short_url
		surl = Googl.shorten(url, "78.10.85.139", "AIzaSyA44HqWr9nSSZARxSBsMNACobm1ntnZAuY").short_url
		update(shortened_url: surl)
	end

	def expand_short_url
		lurl = Googl.expand(shortened_url, "78.10.85.139", "AIzaSyA44HqWr9nSSZARxSBsMNACobm1ntnZAuY")
	end

end

app/models/domain.rb
class Domain < ActiveRecord::Base
	has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
		if params[:tag]
			@bookmarks = Bookmark.tagged_with(params[:tag])
		else
    	@bookmarks = Bookmark.all
		end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create

    @bookmark = Bookmark.new(bookmark_params)
		@bookmark.update_domain
		@bookmark.generate_short_url

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:name, :url, :domain_id,
										 :shortened_id, :tag_list => [])
    end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      params.require(:domain).permit(:domain)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
	<div class="field">
		<%= f.label :tag_list, "Tags (separated by commas)" %></br>
		<%= f.text_field :tag_list %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bookmarks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short Url</th>
      <th>Domain</th> 
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.name %></td>
        <td><a href="<%= bookmark.shortened_url %>"><%= bookmark.shortened_url %></a></td>
        <td><%= Domain.find(bookmark.domain_id).domain %></td> 
        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>ID:</strong>
	<%= @bookmark.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @bookmark.name %>
</p>

<p>
  <strong>URL:</strong>
  <a href="<%= @bookmark.url %>"><%= @bookmark.url %></a>
</p>

<p>
  <strong>Domain:</strong>
  <%= Domain.find(@bookmark.domain_id).domain %>
</p>

<p>
	<strong>Short URL:</strong>
	<a href="<%= @bookmark.shortened_url %>"><%= @bookmark.shortened_url %></a>
</p>

<p>
	<strong>Tags:</strong>
	<%= @bookmark.tag_list %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :domain %><br>
    <%= f.text_field :domain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form' %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Domains</h1>

<table>
  <thead>
    <tr>
			<th>ID</th>
      <th>Domain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr>
				<td><%= domain.id %></td>
        <td><%= domain.domain %></td>
        <td><%= link_to 'Show', domain %></td>
        <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
        <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Domain', new_domain_path %>

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Domain:</strong>
  <%= @domain.domain %>
</p>

<p>
	<strong>ID:</strong>
	<%= @domain.id %>
</p>

<p>
	<strong>Bookmarks linked to this domain</strong>
	<table>
		<tr>
			<th>Name</th>
			<th>URL</th>
		</tr>
		<% Bookmark.all.each do |book| %>
			<% if book.domain_id = @domain.id %>
				<tr>
					<td><%= book.name %></td>
					<td><a href="<%= book.url %>"><%= book.url %></a></td>
				</tr>
			<% end %>
		<% end %>
	</table>
</p>

<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>

app/views/layouts/_header.html.erb
<ul>
	<li><%= link_to "Bookmarks", 	bookmarks_path %></li>
	<li><%= link_to "Domains",		domains_path %></li>
</ul>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookmarksApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	</header>

<%= yield %>

</body>
</html>